const constants = {
	FILTER_TOGGLE: "FILTER_TOGGLE",
	SEARCH_PROJECTS: "SEARCH_PROJECTS",
	TAKE_PROJECT: "TAKE_PROJECT",
	CHANGE_STATUS: "CHANGE_STATUS",
	ADD_NOTE: "ADD_NOTE",
	ADD_DOMAIN: "ADD_DOMAIN",
	ADD_EMAIL: "ADD_EMAIL",
	CHANGE_OWNER: "CHANGE_OWNER",
	SEND_EMAIL: "SEND_EMAIL",
	REFUND_PROJECT: "REFUND_PROJECT",
	ADD_IMP_NOTE: "ADD_IMP_NOTE",
	SCAN_PROJECTS: "SCAN_PROJECTS",
	FINDBY_PROJECTID: "FINDBY_PROJECTID"
}

export default constants
